# Server config
server.port=8080

# DB Config
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Prevent Spring Boot from using H2
spring.sql.init.mode=always
spring.h2.console.enabled=false

# Logging
mpesa.consumer-key=your_key
mpesa.consumer-secret=your_secret
mpesa.business-short-code=174379
mpesa.passkey=your_passkey
mpesa.callback-url=https://yourdomain.com/api/payment/callback
mpesa.access-token-url=https://sandbox.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
mpesa.stk-push-url=https://sandbox.safaricom.co.ke/mpesa/stkpush/v1/processrequest
